### PR TITLE
first implementation of reset

### PR DESCRIPTION
**Pull request by xgreffe**

### CODE REVIEW

**Comment by gamedevdan** [comment]
I think this has introduced a crash in the test project (although it may have been there before) - when I get time I'll check what the issue is, fix it and merge the work. Error is as follows:

ERROR in
action number 1
of Draw Event
for object oController:


DoAdd :: Execution Error
 at gml_Object_oController_Draw_0 (line 164) - 	draw_text_transformed(848,180,"by "+global.GAME_AUTHORS[global.CURRENT_GAME],_strScale,1,0);
############################################################################################
gml_Object_oController_Draw_0 (line 164)

**Comment by xgreffe** [comment]
> I think this has introduced a crash in the test project (although it may have been there before) - when I get time I'll check what the issue is, fix it and merge the work. Error is as follows:
> 
> ERROR in
> action number 1
> of Draw Event
> for object oController:
> 
> DoAdd :: Execution Error
> at gml_Object_oController_Draw_0 (line 164) - draw_text_transformed(848,180,"by "+global.GAME_AUTHORS[global.CURRENT_GAME],_strScale,1,0);
> ############################################################################################
> gml_Object_oController_Draw_0 (line 164)

I saw Evanski post this error earlier on the [forums](https://forum.yoyogames.com/index.php?threads/gmc-jam-player-overhaul.76082/post-503152). Since this branch isn't merged yet I would imagine the problem is already in the main branch. However, I haven't been able to reproduce it on the main branch. I'll try if I can reproduce it on this one.

**Comment by xgreffe** [comment]
> > I think this has introduced a crash in the test project (although it may have been there before) - when I get time I'll check what the issue is, fix it and merge the work. Error is as follows:
> > ERROR in
> > action number 1
> > of Draw Event
> > for object oController:
> > DoAdd :: Execution Error
> > at gml_Object_oController_Draw_0 (line 164) - draw_text_transformed(848,180,"by "+global.GAME_AUTHORS[global.CURRENT_GAME],_strScale,1,0);
> > ############################################################################################
> > gml_Object_oController_Draw_0 (line 164)
> 
> I saw Evanski post this error earlier on the [forums](https://forum.yoyogames.com/index.php?threads/gmc-jam-player-overhaul.76082/post-503152). Since this branch isn't merged yet I would imagine the problem is already in the main branch. However, I haven't been able to reproduce it on the main branch. I'll try if I can reproduce it on this one.

Also can't seem to reproduce this on this branch.
I asked Evanski some questions to narrow down the root cause of the problem.
The fix should be pretty straight forward but want to also know the root cause.
If the problem is already on the main branch and there are no other concerns about this pull request, it can be merged.

**Comment by xgreffe** [comment]
[Evanski confirmed he is using the main branch](https://forum.yoyogames.com/index.php?threads/gmc-jam-player-overhaul.76082/post-503293) so this error is not linked to this pull request.

**Pull request merged**
